language: node_js
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
  - '6'
before_install:
  - stty cols 80
script:
  - npm run test:prod && npm run testci:e2e && npm run build
  - cd demo
  - npm ci
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi