name: PUBLISH

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: npm install

      - name: Build source
        run: npm run build

      - name: Publish packages to npm registry
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Deploy Docs
        run: npm run deploy-docs
